F/osf 25 repo cleanup
OS2Forms/os2forms_forloeb_profile pull request #51
Opened 2023-05-23 08:50 UTC by stanbellcom

2023-05-24 09:46 UTC, martinyde commented on composer.json
> +        "os2forms/os2forms": "dev-f/OSF-25_repo_cleanup",
Awaiting new release of os2forms/os2forms 👍

2023-05-24 09:48 UTC, martinyde requested changes
All good to go and just awaiting release of https://github.com/OS2Forms/os2forms/pull/48
Then change the composer dependency to match new release.

2023-06-13 10:10 UTC, jekuaitk approved these changes

2023-06-13 10:18 UTC, martinyde approved these changes

2023-06-13 11:15 UTC, merged